name:                newhope
version:             0.1.0.0
license:             Apache-2.0
license-file:        LICENSE
github:		     https://github.com/unprolix/newhope
author:              "Jeremy Bornstein"
maintainer:          "jeremy@bornstein.org"
copyright:           "© 2019 Jeremy Bornstein"
homepage: 	     https://github.com/unprolix/newhope#README.md
bug-reports:	     https://github.com/unprolix/newhope/issues


# Metadata for publishing
synopsis:            Library implementing the NewHope cryptographic key-exchange protocol
category:            Library, Cryptography

description:
    This is a Haskell implementation of the NewHope key exchange
    protocol. It has been made via examination of the official NewHope
    project's public domain C reference code and the author is not
    affiliated with that team or with NIST. For further details please
    see the package README.

dependencies:
- base >= 4.7 && < 5

ghc-options:         -Wall -O2

extra-source-files:
- README.md
- ChangeLog.md

# We build a library, but internal targets do not use the library
# since they all want access to non-exported internals.
library:
  source-dirs:
    - src
  exposed-modules:
    - Crypto.NewHope
    - Crypto.NewHope.CCA_KEM
    - Crypto.NewHope.CPA_KEM
    - Crypto.NewHope.RNG
    - Crypto.NewHope.SeedExpander
  dependencies:
    - AES              >= 0.2  && < 0.3
    - bytestring       >= 0.10 && < 0.11
    - containers       >= 0.5  && < 0.7
    - deepseq          >= 1.4  && < 1.5
    - mtl              >= 2.2  && < 2.3
    - vector           >= 0.12 && < 0.13


executables: 

 PQCgenKAT:
    main:              PQCgenKAT.hs
    source-dirs:
    - app/kat
    - auxiliary
    - src
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AES
#   - newhope          # use source because we use internals
    - bytestring
    - containers
    - deepseq
    - mtl
    - system-fileio    >= 0.3  && < 90.4
    - system-filepath  >= 0.4  && < 0.5
    - tasty-quickcheck >= 0.10 && < 0.11
    - text             >= 1.2  && < 1.3
    - vector

 speed:
    main:              Speed.hs
    source-dirs:
    - app/speed
    - auxiliary
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AES
    - bytestring
    - containers
    - deepseq
    - mtl
#   - newhope          # use source because we use internals
    - tasty-quickcheck
    - vector

tests:
  libtest:
    main:              LibTest.hs
    source-dirs:
    - app/libtest
    - auxiliary
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AES
    - HUnit                  >= 1.6  && < 1.7
    - QuickCheck             >= 2.11 && < 2.13
    - bytestring
    - containers
    - deepseq
    - hspec                  >= 2.5  && < 2.7
    - mtl
#   - newhope                # use source because we use internals
    - parallel               >= 3.2  && < 3.3
    - raw-strings-qq         >= 1.1  && < 1.2
    - statistics             >= 0.14 && < 0.16
    - system-fileio
    - system-filepath
    - tasty                  >= 1.1  && < 1.3
    - tasty-expected-failure >= 0.11 && < 0.12
    - tasty-hunit            >= 0.10 && < 0.11
    - tasty-quickcheck
    - text
    - trifecta               >= 2    && < 2.0
    - vector

